// ===== Animal Learning Data =====
// Contains information about 100 common animals

const animalDatabase = [
    { id: 1, name: "Lion", emoji: "🦁", color: "#DAA520" },
    { id: 2, name: "Tiger", emoji: "🐯", color: "#FF8C00" },
    { id: 3, name: "Elephant", emoji: "🐘", color: "#808080" },
    { id: 4, name: "Giraffe", emoji: "🦒", color: "#F4A460" },
    { id: 5, name: "Zebra", emoji: "🦓", color: "#000000" },
    { id: 6, name: "Horse", emoji: "🐴", color: "#8B4513" },
    { id: 7, name: "Cow", emoji: "🐄", color: "#A52A2A" },
    { id: 8, name: "Buffalo", emoji: "🐃", color: "#654321" },
    { id: 9, name: "Goat", emoji: "🐐", color: "#D2B48C" },
    { id: 10, name: "Sheep", emoji: "🐑", color: "#F5F5DC" },
    { id: 11, name: "Dog", emoji: "🐕", color: "#CD853F" },
    { id: 12, name: "Cat", emoji: "🐈", color: "#FF7F50" },
    { id: 13, name: "Rabbit", emoji: "🐇", color: "#FFB6C1" },
    { id: 14, name: "Deer", emoji: "🦌", color: "#BC8F8F" },
    { id: 15, name: "Fox", emoji: "🦊", color: "#FF6347" },
    { id: 16, name: "Wolf", emoji: "🐺", color: "#696969" },
    { id: 17, name: "Bear", emoji: "🐻", color: "#8B4513" },
    { id: 18, name: "Panda", emoji: "🐼", color: "#000000" },
    { id: 19, name: "Kangaroo", emoji: "🦘", color: "#D2691E" },
    { id: 20, name: "Koala", emoji: "🐨", color: "#A9A9A9" },
    { id: 21, name: "Monkey", emoji: "🐒", color: "#CD853F" },
    { id: 22, name: "Chimpanzee", emoji: "🦍", color: "#2F4F4F" },
    { id: 23, name: "Gorilla", emoji: "🦍", color: "#000000" },
    { id: 24, name: "Leopard", emoji: "🐆", color: "#FFD700" },
    { id: 25, name: "Cheetah", emoji: "🐆", color: "#F0E68C" },
    { id: 26, name: "Hyena", emoji: "🐺", color: "#B8860B" },
    { id: 27, name: "Rhinoceros", emoji: "🦏", color: "#708090" },
    { id: 28, name: "Hippopotamus", emoji: "🦛", color: "#778899" },
    { id: 29, name: "Crocodile", emoji: "🐊", color: "#556B2F" },
    { id: 30, name: "Alligator", emoji: "🐊", color: "#2F4F4F" },
    { id: 31, name: "Snake", emoji: "🐍", color: "#6B8E23" },
    { id: 32, name: "Lizard", emoji: "🦎", color: "#9ACD32" },
    { id: 33, name: "Turtle", emoji: "🐢", color: "#228B22" },
    { id: 34, name: "Frog", emoji: "🐸", color: "#32CD32" },
    { id: 35, name: "Toad", emoji: "🐸", color: "#8B7355" },
    { id: 36, name: "Eagle", emoji: "🦅", color: "#8B4513" },
    { id: 37, name: "Hawk", emoji: "🦅", color: "#A0522D" },
    { id: 38, name: "Falcon", emoji: "🦅", color: "#BC8F8F" },
    { id: 39, name: "Owl", emoji: "🦉", color: "#8B7355" },
    { id: 40, name: "Parrot", emoji: "🦜", color: "#00FF00" },
    { id: 41, name: "Peacock", emoji: "🦚", color: "#4169E1" },
    { id: 42, name: "Swan", emoji: "🦢", color: "#FFFAFA" },
    { id: 43, name: "Duck", emoji: "🦆", color: "#FFD700" },
    { id: 44, name: "Goose", emoji: "🦢", color: "#F5F5DC" },
    { id: 45, name: "Hen", emoji: "🐔", color: "#D2691E" },
    { id: 46, name: "Rooster", emoji: "🐓", color: "#DC143C" },
    { id: 47, name: "Pigeon", emoji: "🕊️", color: "#C0C0C0" },
    { id: 48, name: "Sparrow", emoji: "🐦", color: "#A0522D" },
    { id: 49, name: "Crow", emoji: "🐦‍⬛", color: "#000000" },
    { id: 50, name: "Bat", emoji: "🦇", color: "#2F4F4F" },
    { id: 51, name: "Whale", emoji: "🐋", color: "#4682B4" },
    { id: 52, name: "Dolphin", emoji: "🐬", color: "#1E90FF" },
    { id: 53, name: "Shark", emoji: "🦈", color: "#708090" },
    { id: 54, name: "Octopus", emoji: "🐙", color: "#8B008B" },
    { id: 55, name: "Squid", emoji: "🦑", color: "#9370DB" },
    { id: 56, name: "Crab", emoji: "🦀", color: "#DC143C" },
    { id: 57, name: "Lobster", emoji: "🦞", color: "#FF4500" },
    { id: 58, name: "Shrimp", emoji: "🦐", color: "#FFA07A" },
    { id: 59, name: "Seal", emoji: "🦭", color: "#696969" },
    { id: 60, name: "Walrus", emoji: "🦭", color: "#8B7355" },
    { id: 61, name: "Penguin", emoji: "🐧", color: "#000000" },
    { id: 62, name: "Flamingo", emoji: "🦩", color: "#FF69B4" },
    { id: 63, name: "Ostrich", emoji: "🦤", color: "#A0522D" },
    { id: 64, name: "Emu", emoji: "🦤", color: "#8B4513" },
    { id: 65, name: "Camel", emoji: "🐪", color: "#D2B48C" },
    { id: 66, name: "Donkey", emoji: "🫏", color: "#A9A9A9" },
    { id: 67, name: "Mule", emoji: "🫏", color: "#8B7D6B" },
    { id: 68, name: "Yak", emoji: "🦬", color: "#654321" },
    { id: 69, name: "Antelope", emoji: "🦌", color: "#DEB887" },
    { id: 70, name: "Bison", emoji: "🦬", color: "#8B4513" },
    { id: 71, name: "Moose", emoji: "🫎", color: "#A0522D" },
    { id: 72, name: "Otter", emoji: "🦦", color: "#8B7355" },
    { id: 73, name: "Raccoon", emoji: "🦝", color: "#696969" },
    { id: 74, name: "Skunk", emoji: "🦨", color: "#000000" },
    { id: 75, name: "Porcupine", emoji: "🦔", color: "#8B7355" },
    { id: 76, name: "Hedgehog", emoji: "🦔", color: "#D2691E" },
    { id: 77, name: "Squirrel", emoji: "🐿️", color: "#A0522D" },
    { id: 78, name: "Chipmunk", emoji: "🐿️", color: "#CD853F" },
    { id: 79, name: "Armadillo", emoji: "🦡", color: "#808080" },
    { id: 80, name: "Sloth", emoji: "🦥", color: "#8B7355" },
    { id: 81, name: "Meerkat", emoji: "🦦", color: "#D2B48C" },
    { id: 82, name: "Lemur", emoji: "🐵", color: "#A9A9A9" },
    { id: 83, name: "Baboon", emoji: "🐵", color: "#A0522D" },
    { id: 84, name: "Jaguar", emoji: "🐆", color: "#FFD700" },
    { id: 85, name: "Panther", emoji: "🐆", color: "#000000" },
    { id: 86, name: "Cougar", emoji: "🐈", color: "#D2691E" },
    { id: 87, name: "Polar Bear", emoji: "🐻‍❄️", color: "#F0FFFF" },
    { id: 88, name: "Grizzly Bear", emoji: "🐻", color: "#8B4513" },
    { id: 89, name: "Red Panda", emoji: "🐼", color: "#FF6347" },
    { id: 90, name: "Tasmanian Devil", emoji: "🦊", color: "#2F4F4F" },
    { id: 91, name: "Wombat", emoji: "🐻", color: "#A0522D" },
    { id: 92, name: "Platypus", emoji: "🦦", color: "#8B7355" },
    { id: 93, name: "Iguana", emoji: "🦎", color: "#32CD32" },
    { id: 94, name: "Chameleon", emoji: "🦎", color: "#7FFF00" },
    { id: 95, name: "Komodo Dragon", emoji: "🦎", color: "#556B2F" },
    { id: 96, name: "Blue Whale", emoji: "🐋", color: "#4169E1" },
    { id: 97, name: "Hammerhead Shark", emoji: "🦈", color: "#708090" },
    { id: 98, name: "Starfish", emoji: "⭐", color: "#FF6347" },
    { id: 99, name: "Seahorse", emoji: "🐴", color: "#48D1CC" },
    { id: 100, name: "Jellyfish", emoji: "🪼", color: "#DA70D6" }
];
