// ===== Animal Learning Data =====
// Contains information about 100 common animals with Bengali names

const animalDatabase = [
    { id: 1, name: "Lion", bengaliName: "সিংহ", emoji: "🦁", color: "#DAA520" },
    { id: 2, name: "Tiger", bengaliName: "বাঘ", emoji: "🐯", color: "#FF8C00" },
    { id: 3, name: "Elephant", bengaliName: "হাতি", emoji: "🐘", color: "#808080" },
    { id: 4, name: "Giraffe", bengaliName: "জিরাফ", emoji: "🦒", color: "#F4A460" },
    { id: 5, name: "Zebra", bengaliName: "জেব্রা", emoji: "🦓", color: "#000000" },
    { id: 6, name: "Horse", bengaliName: "ঘোড়া", emoji: "🐴", color: "#8B4513" },
    { id: 7, name: "Cow", bengaliName: "গরু", emoji: "🐄", color: "#A52A2A" },
    { id: 8, name: "Buffalo", bengaliName: "মহিষ", emoji: "🐃", color: "#654321" },
    { id: 9, name: "Goat", bengaliName: "ছাগল", emoji: "🐐", color: "#D2B48C" },
    { id: 10, name: "Sheep", bengaliName: "ভেড়া", emoji: "🐑", color: "#F5F5DC" },
    { id: 11, name: "Dog", bengaliName: "কুকুর", emoji: "🐕", color: "#CD853F" },
    { id: 12, name: "Cat", bengaliName: "বিড়াল", emoji: "🐈", color: "#FF7F50" },
    { id: 13, name: "Rabbit", bengaliName: "খরগোশ", emoji: "🐇", color: "#FFB6C1" },
    { id: 14, name: "Deer", bengaliName: "হরিণ", emoji: "🦌", color: "#BC8F8F" },
    { id: 15, name: "Fox", bengaliName: "শিয়াল", emoji: "🦊", color: "#FF6347" },
    { id: 16, name: "Wolf", bengaliName: "নেকড়ে", emoji: "🐺", color: "#696969" },
    { id: 17, name: "Bear", bengaliName: "ভাল্লুক", emoji: "🐻", color: "#8B4513" },
    { id: 18, name: "Panda", bengaliName: "পান্ডা", emoji: "🐼", color: "#000000" },
    { id: 19, name: "Kangaroo", bengaliName: "ক্যাঙ্গারু", emoji: "🦘", color: "#D2691E" },
    { id: 20, name: "Koala", bengaliName: "কোয়ালা", emoji: "🐨", color: "#A9A9A9" },
    { id: 21, name: "Monkey", bengaliName: "বানর", emoji: "🐒", color: "#CD853F" },
    { id: 22, name: "Chimpanzee", bengaliName: "শিম্পাঞ্জি", emoji: "🦍", color: "#2F4F4F" },
    { id: 23, name: "Gorilla", bengaliName: "গরিলা", emoji: "🦍", color: "#000000" },
    { id: 24, name: "Leopard", bengaliName: "চিতাবাঘ", emoji: "🐆", color: "#FFD700" },
    { id: 25, name: "Cheetah", bengaliName: "চিতা", emoji: "🐆", color: "#F0E68C" },
    { id: 26, name: "Hyena", bengaliName: "হায়েনা", emoji: "🐺", color: "#B8860B" },
    { id: 27, name: "Rhinoceros", bengaliName: "গন্ডার", emoji: "🦏", color: "#708090" },
    { id: 28, name: "Hippopotamus", bengaliName: "জলহস্তী", emoji: "🦛", color: "#778899" },
    { id: 29, name: "Crocodile", bengaliName: "কুমির", emoji: "🐊", color: "#556B2F" },
    { id: 30, name: "Alligator", bengaliName: "অ্যালিগেটর", emoji: "🐊", color: "#2F4F4F" },
    { id: 31, name: "Snake", bengaliName: "সাপ", emoji: "🐍", color: "#6B8E23" },
    { id: 32, name: "Lizard", bengaliName: "টিকটিকি", emoji: "🦎", color: "#9ACD32" },
    { id: 33, name: "Turtle", bengaliName: "কচ্ছপ", emoji: "🐢", color: "#228B22" },
    { id: 34, name: "Frog", bengaliName: "ব্যাঙ", emoji: "🐸", color: "#32CD32" },
    { id: 35, name: "Toad", bengaliName: "কুনোব্যাঙ", emoji: "🐸", color: "#8B7355" },
    { id: 36, name: "Eagle", bengaliName: "ঈগল", emoji: "🦅", color: "#8B4513" },
    { id: 37, name: "Hawk", bengaliName: "বাজপাখি", emoji: "🦅", color: "#A0522D" },
    { id: 38, name: "Falcon", bengaliName: "ফ্যালকন", emoji: "🦅", color: "#BC8F8F" },
    { id: 39, name: "Owl", bengaliName: "পেঁচা", emoji: "🦉", color: "#8B7355" },
    { id: 40, name: "Parrot", bengaliName: "টিয়া", emoji: "🦜", color: "#00FF00" },
    { id: 41, name: "Peacock", bengaliName: "ময়ূর", emoji: "🦚", color: "#4169E1" },
    { id: 42, name: "Swan", bengaliName: "রাজহাঁস", emoji: "🦢", color: "#FFFAFA" },
    { id: 43, name: "Duck", bengaliName: "হাঁস", emoji: "🦆", color: "#FFD700" },
    { id: 44, name: "Goose", bengaliName: "রাজহাঁস", emoji: "🦢", color: "#F5F5DC" },
    { id: 45, name: "Hen", bengaliName: "মুরগি", emoji: "🐔", color: "#D2691E" },
    { id: 46, name: "Rooster", bengaliName: "মোরগ", emoji: "🐓", color: "#DC143C" },
    { id: 47, name: "Pigeon", bengaliName: "পায়রা", emoji: "🕊️", color: "#C0C0C0" },
    { id: 48, name: "Sparrow", bengaliName: "চড়ুই", emoji: "🐦", color: "#A0522D" },
    { id: 49, name: "Crow", bengaliName: "কাক", emoji: "🐦‍⬛", color: "#000000" },
    { id: 50, name: "Bat", bengaliName: "বাদুড়", emoji: "🦇", color: "#2F4F4F" },
    { id: 51, name: "Whale", bengaliName: "তিমি", emoji: "🐋", color: "#4682B4" },
    { id: 52, name: "Dolphin", bengaliName: "ডলফিন", emoji: "🐬", color: "#1E90FF" },
    { id: 53, name: "Shark", bengaliName: "হাঙর", emoji: "🦈", color: "#708090" },
    { id: 54, name: "Octopus", bengaliName: "অক্টোপাস", emoji: "🐙", color: "#8B008B" },
    { id: 55, name: "Squid", bengaliName: "স্কুইড", emoji: "🦑", color: "#9370DB" },
    { id: 56, name: "Crab", bengaliName: "কাঁকড়া", emoji: "🦀", color: "#DC143C" },
    { id: 57, name: "Lobster", bengaliName: "লবস্টার", emoji: "🦞", color: "#FF4500" },
    { id: 58, name: "Shrimp", bengaliName: "চিংড়ি", emoji: "🦐", color: "#FFA07A" },
    { id: 59, name: "Seal", bengaliName: "সিল মাছ", emoji: "🦭", color: "#696969" },
    { id: 60, name: "Walrus", bengaliName: "ওয়ালরাস", emoji: "🦭", color: "#8B7355" },
    { id: 61, name: "Penguin", bengaliName: "পেঙ্গুইন", emoji: "🐧", color: "#000000" },
    { id: 62, name: "Flamingo", bengaliName: "ফ্ল্যামিঙ্গো", emoji: "🦩", color: "#FF69B4" },
    { id: 63, name: "Ostrich", bengaliName: "উটপাখি", emoji: "🦤", color: "#A0522D" },
    { id: 64, name: "Emu", bengaliName: "এমু পাখি", emoji: "🦤", color: "#8B4513" },
    { id: 65, name: "Camel", bengaliName: "উট", emoji: "🐪", color: "#D2B48C" },
    { id: 66, name: "Donkey", bengaliName: "গাধা", emoji: "🫏", color: "#A9A9A9" },
    { id: 67, name: "Mule", bengaliName: "খচ্চর", emoji: "🫏", color: "#8B7D6B" },
    { id: 68, name: "Yak", bengaliName: "ইয়াক", emoji: "🦬", color: "#654321" },
    { id: 69, name: "Antelope", bengaliName: "এন্টিলোপ", emoji: "🦌", color: "#DEB887" },
    { id: 70, name: "Bison", bengaliName: "বাইসন", emoji: "🦬", color: "#8B4513" },
    { id: 71, name: "Moose", bengaliName: "মুজ", emoji: "🫎", color: "#A0522D" },
    { id: 72, name: "Otter", bengaliName: "ওটার", emoji: "🦦", color: "#8B7355" },
    { id: 73, name: "Raccoon", bengaliName: "র‍্যাকুন", emoji: "🦝", color: "#696969" },
    { id: 74, name: "Skunk", bengaliName: "স্কাঙ্ক", emoji: "🦨", color: "#000000" },
    { id: 75, name: "Porcupine", bengaliName: "সজারু", emoji: "🦔", color: "#8B7355" },
    { id: 76, name: "Hedgehog", bengaliName: "হেজহগ", emoji: "🦔", color: "#D2691E" },
    { id: 77, name: "Squirrel", bengaliName: "কাঠবিড়ালি", emoji: "🐿️", color: "#A0522D" },
    { id: 78, name: "Chipmunk", bengaliName: "চিপমাঙ্ক", emoji: "🐿️", color: "#CD853F" },
    { id: 79, name: "Armadillo", bengaliName: "আর্মাডিলো", emoji: "🦡", color: "#808080" },
    { id: 80, name: "Sloth", bengaliName: "স্লথ", emoji: "🦥", color: "#8B7355" },
    { id: 81, name: "Meerkat", bengaliName: "মিরক্যাট", emoji: "🦦", color: "#D2B48C" },
    { id: 82, name: "Lemur", bengaliName: "লেমুর", emoji: "🐵", color: "#A9A9A9" },
    { id: 83, name: "Baboon", bengaliName: "বেবুন", emoji: "🐵", color: "#A0522D" },
    { id: 84, name: "Jaguar", bengaliName: "জাগুয়ার", emoji: "🐆", color: "#FFD700" },
    { id: 85, name: "Panther", bengaliName: "প্যান্থার", emoji: "🐆", color: "#000000" },
    { id: 86, name: "Cougar", bengaliName: "কুগার", emoji: "🐈", color: "#D2691E" },
    { id: 87, name: "Polar Bear", bengaliName: "মেরু ভাল্লুক", emoji: "🐻‍❄️", color: "#F0FFFF" },
    { id: 88, name: "Grizzly Bear", bengaliName: "গ্রিজলি বিয়ার", emoji: "🐻", color: "#8B4513" },
    { id: 89, name: "Red Panda", bengaliName: "লাল পান্ডা", emoji: "🐼", color: "#FF6347" },
    { id: 90, name: "Tasmanian Devil", bengaliName: "টাসমেনিয়ান ডেভিল", emoji: "🦊", color: "#2F4F4F" },
    { id: 91, name: "Wombat", bengaliName: "ওমব্যাট", emoji: "🐻", color: "#A0522D" },
    { id: 92, name: "Platypus", bengaliName: "প্ল্যাটিপাস", emoji: "🦦", color: "#8B7355" },
    { id: 93, name: "Iguana", bengaliName: "ইগুয়ানা", emoji: "🦎", color: "#32CD32" },
    { id: 94, name: "Chameleon", bengaliName: "গিরগিটি", emoji: "🦎", color: "#7FFF00" },
    { id: 95, name: "Komodo Dragon", bengaliName: "কোমোডো ড্রাগন", emoji: "🦎", color: "#556B2F" },
    { id: 96, name: "Blue Whale", bengaliName: "নীল তিমি", emoji: "🐋", color: "#4169E1" },
    { id: 97, name: "Hammerhead Shark", bengaliName: "হ্যামারহেড হাঙর", emoji: "🦈", color: "#708090" },
    { id: 98, name: "Starfish", bengaliName: "তারা মাছ", emoji: "⭐", color: "#FF6347" },
    { id: 99, name: "Seahorse", bengaliName: "সামুদ্রিক ঘোড়া", emoji: "🐴", color: "#48D1CC" },
    { id: 100, name: "Jellyfish", bengaliName: "জেলিফিশ", emoji: "🪼", color: "#DA70D6" }
];
