// ===== Birds Learning Data =====
// Contains information about 100 bird species

const birdsDatabase = [
    { id: 1, name: "Eagle", emoji: "🦅", color: "#8B4513", type: "Raptor" },
    { id: 2, name: "Bald Eagle", emoji: "🦅", color: "#654321", type: "Raptor" },
    { id: 3, name: "Golden Eagle", emoji: "🦅", color: "#DAA520", type: "Raptor" },
    { id: 4, name: "Hawk", emoji: "🦅", color: "#8B7355", type: "Raptor" },
    { id: 5, name: "Falcon", emoji: "🦅", color: "#A0522D", type: "Raptor" },
    { id: 6, name: "Peregrine Falcon", emoji: "🦅", color: "#708090", type: "Raptor" },
    { id: 7, name: "Owl", emoji: "🦉", color: "#8B6914", type: "Night" },
    { id: 8, name: "Barn Owl", emoji: "🦉", color: "#D2B48C", type: "Night" },
    { id: 9, name: "Snowy Owl", emoji: "🦉", color: "#F0F8FF", type: "Arctic" },
    { id: 10, name: "Parrot", emoji: "🦜", color: "#32CD32", type: "Tropical" },
    { id: 11, name: "Macaw", emoji: "🦜", color: "#FF4500", type: "Tropical" },
    { id: 12, name: "Cockatoo", emoji: "🦜", color: "#FFFACD", type: "Tropical" },
    { id: 13, name: "Budgerigar", emoji: "🦜", color: "#00CED1", type: "Pet" },
    { id: 14, name: "Canary", emoji: "🐤", color: "#FFFF00", type: "Song" },
    { id: 15, name: "Lovebird", emoji: "🦜", color: "#FF69B4", type: "Pet" },
    { id: 16, name: "Finch", emoji: "🐤", color: "#DEB887", type: "Song" },
    { id: 17, name: "Sparrow", emoji: "🐦", color: "#8B7D6B", type: "Garden" },
    { id: 18, name: "House Sparrow", emoji: "🕊️", color: "#A0826D", type: "City" },
    { id: 19, name: "Crow", emoji: "🐦‍⬛", color: "#000000", type: "Smart" },
    { id: 20, name: "Raven", emoji: "🐦‍⬛", color: "#1C1C1C", type: "Smart" },
    { id: 21, name: "Pigeon", emoji: "🕊️", color: "#808080", type: "City" },
    { id: 22, name: "Dove", emoji: "🕊️", color: "#FFFFFF", type: "Peace" },
    { id: 23, name: "Peacock", emoji: "🦚", color: "#4169E1", type: "Fancy" },
    { id: 24, name: "Peahen", emoji: "🦚", color: "#6B8E23", type: "Fancy" },
    { id: 25, name: "Swan", emoji: "🦢", color: "#FFFAFA", type: "Elegant" },
    { id: 26, name: "Black Swan", emoji: "🦢", color: "#2F4F4F", type: "Elegant" },
    { id: 27, name: "Duck", emoji: "🦆", color: "#FFD700", type: "Water" },
    { id: 28, name: "Mallard", emoji: "🦆", color: "#006400", type: "Water" },
    { id: 29, name: "Goose", emoji: "🦆", color: "#F5F5DC", type: "Farm" },
    { id: 30, name: "Flamingo", emoji: "🦩", color: "#FF1493", type: "Exotic" },
    { id: 31, name: "Ostrich", emoji: "🦤", color: "#D2691E", type: "Large" },
    { id: 32, name: "Emu", emoji: "🦤", color: "#8B4513", type: "Large" },
    { id: 33, name: "Penguin", emoji: "🐧", color: "#4682B4", type: "Polar" },
    { id: 34, name: "King Penguin", emoji: "🐧", color: "#FF8C00", type: "Polar" },
    { id: 35, name: "Woodpecker", emoji: "🦜", color: "#DC143C", type: "Forest" },
    { id: 36, name: "Kingfisher", emoji: "🐦", color: "#1E90FF", type: "Fisher" },
    { id: 37, name: "Seagull", emoji: "🕊️", color: "#E0E0E0", type: "Coast" },
    { id: 38, name: "Albatross", emoji: "🦅", color: "#F0F0F0", type: "Ocean" },
    { id: 39, name: "Pelican", emoji: "🦆", color: "#FFA07A", type: "Fisher" },
    { id: 40, name: "Heron", emoji: "🦢", color: "#4682B4", type: "Wader" },
    { id: 41, name: "Crane", emoji: "🦢", color: "#D3D3D3", type: "Wader" },
    { id: 42, name: "Stork", emoji: "🦩", color: "#FFFFFF", type: "Wader" },
    { id: 43, name: "Vulture", emoji: "🦅", color: "#696969", type: "Raptor" },
    { id: 44, name: "Kite", emoji: "🦅", color: "#8B4513", type: "Raptor" },
    { id: 45, name: "Magpie", emoji: "🐦‍⬛", color: "#000080", type: "Smart" },
    { id: 46, name: "Robin", emoji: "🐤", color: "#CD5C5C", type: "Garden" },
    { id: 47, name: "Blue Jay", emoji: "🐦", color: "#4169E1", type: "Bold" },
    { id: 48, name: "Cardinal", emoji: "🦜", color: "#DC143C", type: "Bright" },
    { id: 49, name: "Hummingbird", emoji: "🐦", color: "#00FF7F", type: "Tiny" },
    { id: 50, name: "Toucan", emoji: "🦜", color: "#FF8C00", type: "Tropical" },
    { id: 51, name: "Hornbill", emoji: "🦜", color: "#FFD700", type: "Tropical" },
    { id: 52, name: "Nightjar", emoji: "🦉", color: "#8B7355", type: "Night" },
    { id: 53, name: "Cuckoo", emoji: "🕊️", color: "#808080", type: "Mimic" },
    { id: 54, name: "Koel", emoji: "🐦‍⬛", color: "#000000", type: "Caller" },
    { id: 55, name: "Swallow", emoji: "🐦", color: "#4682B4", type: "Fast" },
    { id: 56, name: "Swift", emoji: "🐦", color: "#2F4F4F", type: "Fast" },
    { id: 57, name: "Skylark", emoji: "🐤", color: "#D2B48C", type: "Song" },
    { id: 58, name: "Nightingale", emoji: "🐦", color: "#A0826D", type: "Song" },
    { id: 59, name: "Wren", emoji: "🐤", color: "#8B7355", type: "Small" },
    { id: 60, name: "Goldfinch", emoji: "🐦", color: "#FFD700", type: "Song" },
    { id: 61, name: "Chaffinch", emoji: "🕊️", color: "#CD5C5C", type: "Common" },
    { id: 62, name: "Starling", emoji: "🐦‍⬛", color: "#2F4F4F", type: "Flock" },
    { id: 63, name: "Mockingbird", emoji: "🐦", color: "#808080", type: "Mimic" },
    { id: 64, name: "Oriole", emoji: "🦜", color: "#FF8C00", type: "Bright" },
    { id: 65, name: "Waxwing", emoji: "🐦", color: "#CD853F", type: "Sleek" },
    { id: 66, name: "Sandpiper", emoji: "🕊️", color: "#D2B48C", type: "Shore" },
    { id: 67, name: "Lapwing", emoji: "🐦", color: "#228B22", type: "Field" },
    { id: 68, name: "Quail", emoji: "🐤", color: "#8B7355", type: "Ground" },
    { id: 69, name: "Partridge", emoji: "🐦", color: "#A0522D", type: "Game" },
    { id: 70, name: "Pheasant", emoji: "🦚", color: "#B8860B", type: "Game" },
    { id: 71, name: "Turkey", emoji: "🦃", color: "#8B4513", type: "Large" },
    { id: 72, name: "Guinea Fowl", emoji: "🦃", color: "#696969", type: "Farm" },
    { id: 73, name: "Condor", emoji: "🦅", color: "#000000", type: "Giant" },
    { id: 74, name: "Secretary Bird", emoji: "🦅", color: "#D3D3D3", type: "Hunter" },
    { id: 75, name: "Cassowary", emoji: "🦤", color: "#000080", type: "Danger" },
    { id: 76, name: "Roadrunner", emoji: "🐦", color: "#8B7355", type: "Fast" },
    { id: 77, name: "Hoopoe", emoji: "🦜", color: "#FF8C00", type: "Crest" },
    { id: 78, name: "Bee-eater", emoji: "🐦", color: "#00CED1", type: "Bright" },
    { id: 79, name: "Sunbird", emoji: "🐤", color: "#FFD700", type: "Nectar" },
    { id: 80, name: "Tern", emoji: "🕊️", color: "#ADD8E6", type: "Sea" },
    { id: 81, name: "Gannet", emoji: "🦆", color: "#F0F8FF", type: "Diver" },
    { id: 82, name: "Cormorant", emoji: "🐦‍⬛", color: "#2F4F4F", type: "Diver" },
    { id: 83, name: "Ibis", emoji: "🦩", color: "#FFFACD", type: "Wader" },
    { id: 84, name: "Egret", emoji: "🦢", color: "#FFFFFF", type: "Elegant" },
    { id: 85, name: "Bittern", emoji: "🦆", color: "#BDB76B", type: "Marsh" },
    { id: 86, name: "Shrike", emoji: "🐦", color: "#808080", type: "Hunter" },
    { id: 87, name: "Bulbul", emoji: "🐤", color: "#A0826D", type: "Song" },
    { id: 88, name: "Drongo", emoji: "🐦‍⬛", color: "#000000", type: "Bold" },
    { id: 89, name: "Myna", emoji: "🐦", color: "#8B7355", type: "Talker" },
    { id: 90, name: "Weaver Bird", emoji: "🦜", color: "#FFD700", type: "Builder" },
    { id: 91, name: "Crossbill", emoji: "🦜", color: "#DC143C", type: "Unique" },
    { id: 92, name: "Loon", emoji: "🦆", color: "#2F4F4F", type: "Diver" },
    { id: 93, name: "Grebe", emoji: "🦆", color: "#696969", type: "Water" },
    { id: 94, name: "Ptarmigan", emoji: "🕊️", color: "#F0F0F0", type: "Arctic" },
    { id: 95, name: "Avocet", emoji: "🦢", color: "#E0E0E0", type: "Wader" },
    { id: 96, name: "Spoonbill", emoji: "🦩", color: "#FFB6C1", type: "Wader" },
    { id: 97, name: "Chickadee", emoji: "🐤", color: "#A9A9A9", type: "Cute" },
    { id: 98, name: "Nuthatch", emoji: "🐦", color: "#B0C4DE", type: "Climber" },
    { id: 99, name: "Warbler", emoji: "🐦", color: "#9ACD32", type: "Song" },
    { id: 100, name: "Thrush", emoji: "🐦", color: "#8B6914", type: "Song" }
];
