// ===== Birds Learning Data =====
// Contains information about 100 bird species with Bengali names

const birdsDatabase = [
    { id: 1, name: "Eagle", bengaliName: "ঈগল", emoji: "🦅", color: "#8B4513", type: "Raptor" },
    { id: 2, name: "Bald Eagle", bengaliName: "টাক ঈগল", emoji: "🦅", color: "#654321", type: "Raptor" },
    { id: 3, name: "Golden Eagle", bengaliName: "সোনালি ঈগল", emoji: "🦅", color: "#DAA520", type: "Raptor" },
    { id: 4, name: "Hawk", bengaliName: "বাজপাখি", emoji: "🦅", color: "#8B7355", type: "Raptor" },
    { id: 5, name: "Falcon", bengaliName: "ফ্যালকন", emoji: "🦅", color: "#A0522D", type: "Raptor" },
    { id: 6, name: "Peregrine Falcon", bengaliName: "পেরেগ্রিন ফ্যালকন", emoji: "🦅", color: "#708090", type: "Raptor" },
    { id: 7, name: "Owl", bengaliName: "পেঁচা", emoji: "🦉", color: "#8B6914", type: "Night" },
    { id: 8, name: "Barn Owl", bengaliName: "শস্যাগার পেঁচা", emoji: "🦉", color: "#D2B48C", type: "Night" },
    { id: 9, name: "Snowy Owl", bengaliName: "তুষার পেঁচা", emoji: "🦉", color: "#F0F8FF", type: "Arctic" },
    { id: 10, name: "Parrot", bengaliName: "টিয়া", emoji: "🦜", color: "#32CD32", type: "Tropical" },
    { id: 11, name: "Macaw", bengaliName: "ম্যাকাও", emoji: "🦜", color: "#FF4500", type: "Tropical" },
    { id: 12, name: "Cockatoo", bengaliName: "ককাটু", emoji: "🦜", color: "#FFFACD", type: "Tropical" },
    { id: 13, name: "Budgerigar", bengaliName: "বাজরিগার", emoji: "🦜", color: "#00CED1", type: "Pet" },
    { id: 14, name: "Canary", bengaliName: "ক্যানারি", emoji: "🐤", color: "#FFFF00", type: "Song" },
    { id: 15, name: "Lovebird", bengaliName: "লাভবার্ড", emoji: "🦜", color: "#FF69B4", type: "Pet" },
    { id: 16, name: "Finch", bengaliName: "ফিঞ্চ", emoji: "🐤", color: "#DEB887", type: "Song" },
    { id: 17, name: "Sparrow", bengaliName: "চড়ুই", emoji: "🐦", color: "#8B7D6B", type: "Garden" },
    { id: 18, name: "House Sparrow", bengaliName: "ঘর চড়ুই", emoji: "🕊️", color: "#A0826D", type: "City" },
    { id: 19, name: "Crow", bengaliName: "কাক", emoji: "🐦‍⬛", color: "#000000", type: "Smart" },
    { id: 20, name: "Raven", bengaliName: "দাঁড়কাক", emoji: "🐦‍⬛", color: "#1C1C1C", type: "Smart" },
    { id: 21, name: "Pigeon", bengaliName: "পায়রা", emoji: "🕊️", color: "#808080", type: "City" },
    { id: 22, name: "Dove", bengaliName: "কবুতর", emoji: "🕊️", color: "#FFFFFF", type: "Peace" },
    { id: 23, name: "Peacock", bengaliName: "ময়ূর", emoji: "🦚", color: "#4169E1", type: "Fancy" },
    { id: 24, name: "Peahen", bengaliName: "ময়ূরী", emoji: "🦚", color: "#6B8E23", type: "Fancy" },
    { id: 25, name: "Swan", bengaliName: "রাজহাঁস", emoji: "🦢", color: "#FFFAFA", type: "Elegant" },
    { id: 26, name: "Black Swan", bengaliName: "কালো রাজহাঁস", emoji: "🦢", color: "#2F4F4F", type: "Elegant" },
    { id: 27, name: "Duck", bengaliName: "হাঁস", emoji: "🦆", color: "#FFD700", type: "Water" },
    { id: 28, name: "Mallard", bengaliName: "ম্যালার্ড হাঁস", emoji: "🦆", color: "#006400", type: "Water" },
    { id: 29, name: "Goose", bengaliName: "রাজহাঁস", emoji: "🦆", color: "#F5F5DC", type: "Farm" },
    { id: 30, name: "Flamingo", bengaliName: "ফ্ল্যামিঙ্গো", emoji: "🦩", color: "#FF1493", type: "Exotic" },
    { id: 31, name: "Ostrich", bengaliName: "উটপাখি", emoji: "🦤", color: "#D2691E", type: "Large" },
    { id: 32, name: "Emu", bengaliName: "এমু পাখি", emoji: "🦤", color: "#8B4513", type: "Large" },
    { id: 33, name: "Penguin", bengaliName: "পেঙ্গুইন", emoji: "🐧", color: "#4682B4", type: "Polar" },
    { id: 34, name: "King Penguin", bengaliName: "রাজা পেঙ্গুইন", emoji: "🐧", color: "#FF8C00", type: "Polar" },
    { id: 35, name: "Woodpecker", bengaliName: "কাঠঠোকরা", emoji: "🦜", color: "#DC143C", type: "Forest" },
    { id: 36, name: "Kingfisher", bengaliName: "মাছরাঙা", emoji: "🐦", color: "#1E90FF", type: "Fisher" },
    { id: 37, name: "Seagull", bengaliName: "সিগাল", emoji: "🕊️", color: "#E0E0E0", type: "Coast" },
    { id: 38, name: "Albatross", bengaliName: "আলবাট্রস", emoji: "🦅", color: "#F0F0F0", type: "Ocean" },
    { id: 39, name: "Pelican", bengaliName: "পেলিকান", emoji: "🦆", color: "#FFA07A", type: "Fisher" },
    { id: 40, name: "Heron", bengaliName: "বক", emoji: "🦢", color: "#4682B4", type: "Wader" },
    { id: 41, name: "Crane", bengaliName: "সারস", emoji: "🦢", color: "#D3D3D3", type: "Wader" },
    { id: 42, name: "Stork", bengaliName: "সারস", emoji: "🦩", color: "#FFFFFF", type: "Wader" },
    { id: 43, name: "Vulture", bengaliName: "শকুন", emoji: "🦅", color: "#696969", type: "Raptor" },
    { id: 44, name: "Kite", bengaliName: "চিল", emoji: "🦅", color: "#8B4513", type: "Raptor" },
    { id: 45, name: "Magpie", bengaliName: "ম্যাগপাই", emoji: "🐦‍⬛", color: "#000080", type: "Smart" },
    { id: 46, name: "Robin", bengaliName: "রবিন", emoji: "🐤", color: "#CD5C5C", type: "Garden" },
    { id: 47, name: "Blue Jay", bengaliName: "নীল জে", emoji: "🐦", color: "#4169E1", type: "Bold" },
    { id: 48, name: "Cardinal", bengaliName: "কার্ডিনাল", emoji: "🦜", color: "#DC143C", type: "Bright" },
    { id: 49, name: "Hummingbird", bengaliName: "হামিংবার্ড", emoji: "🐦", color: "#00FF7F", type: "Tiny" },
    { id: 50, name: "Toucan", bengaliName: "টুকান", emoji: "🦜", color: "#FF8C00", type: "Tropical" },
    { id: 51, name: "Hornbill", bengaliName: "ধনেশ", emoji: "🦜", color: "#FFD700", type: "Tropical" },
    { id: 52, name: "Nightjar", bengaliName: "রাত্রিচর পাখি", emoji: "🦉", color: "#8B7355", type: "Night" },
    { id: 53, name: "Cuckoo", bengaliName: "কোকিল", emoji: "🕊️", color: "#808080", type: "Mimic" },
    { id: 54, name: "Koel", bengaliName: "কোয়েল", emoji: "🐦‍⬛", color: "#000000", type: "Caller" },
    { id: 55, name: "Swallow", bengaliName: "আবাবিল", emoji: "🐦", color: "#4682B4", type: "Fast" },
    { id: 56, name: "Swift", bengaliName: "সুইফট", emoji: "🐦", color: "#2F4F4F", type: "Fast" },
    { id: 57, name: "Skylark", bengaliName: "স্কাইলার্ক", emoji: "🐤", color: "#D2B48C", type: "Song" },
    { id: 58, name: "Nightingale", bengaliName: "বুলবুলি", emoji: "🐦", color: "#A0826D", type: "Song" },
    { id: 59, name: "Wren", bengaliName: "রেন পাখি", emoji: "🐤", color: "#8B7355", type: "Small" },
    { id: 60, name: "Goldfinch", bengaliName: "সোনালি ফিঞ্চ", emoji: "🐦", color: "#FFD700", type: "Song" },
    { id: 61, name: "Chaffinch", bengaliName: "চ্যাফিঞ্চ", emoji: "🕊️", color: "#CD5C5C", type: "Common" },
    { id: 62, name: "Starling", bengaliName: "স্টারলিং", emoji: "🐦‍⬛", color: "#2F4F4F", type: "Flock" },
    { id: 63, name: "Mockingbird", bengaliName: "মকিংবার্ড", emoji: "🐦", color: "#808080", type: "Mimic" },
    { id: 64, name: "Oriole", bengaliName: "ওরিওল", emoji: "🦜", color: "#FF8C00", type: "Bright" },
    { id: 65, name: "Waxwing", bengaliName: "ওয়াক্সউইং", emoji: "🐦", color: "#CD853F", type: "Sleek" },
    { id: 66, name: "Sandpiper", bengaliName: "স্যান্ডপাইপার", emoji: "🕊️", color: "#D2B48C", type: "Shore" },
    { id: 67, name: "Lapwing", bengaliName: "ল্যাপউইং", emoji: "🐦", color: "#228B22", type: "Field" },
    { id: 68, name: "Quail", bengaliName: "ভাটুরা", emoji: "🐤", color: "#8B7355", type: "Ground" },
    { id: 69, name: "Partridge", bengaliName: "তিতির", emoji: "🐦", color: "#A0522D", type: "Game" },
    { id: 70, name: "Pheasant", bengaliName: "তিতির", emoji: "🦚", color: "#B8860B", type: "Game" },
    { id: 71, name: "Turkey", bengaliName: "টার্কি", emoji: "🦃", color: "#8B4513", type: "Large" },
    { id: 72, name: "Guinea Fowl", bengaliName: "গিনি মুরগি", emoji: "🦃", color: "#696969", type: "Farm" },
    { id: 73, name: "Condor", bengaliName: "কনডর", emoji: "🦅", color: "#000000", type: "Giant" },
    { id: 74, name: "Secretary Bird", bengaliName: "সেক্রেটারি পাখি", emoji: "🦅", color: "#D3D3D3", type: "Hunter" },
    { id: 75, name: "Cassowary", bengaliName: "ক্যাসোয়ারি", emoji: "🦤", color: "#000080", type: "Danger" },
    { id: 76, name: "Roadrunner", bengaliName: "রোডরানার", emoji: "🐦", color: "#8B7355", type: "Fast" },
    { id: 77, name: "Hoopoe", bengaliName: "হুদহুদ", emoji: "🦜", color: "#FF8C00", type: "Crest" },
    { id: 78, name: "Bee-eater", bengaliName: "মৌমাছি খাদক", emoji: "🐦", color: "#00CED1", type: "Bright" },
    { id: 79, name: "Sunbird", bengaliName: "সূর্যপাখি", emoji: "🐤", color: "#FFD700", type: "Nectar" },
    { id: 80, name: "Tern", bengaliName: "টার্ন", emoji: "🕊️", color: "#ADD8E6", type: "Sea" },
    { id: 81, name: "Gannet", bengaliName: "গ্যানেট", emoji: "🦆", color: "#F0F8FF", type: "Diver" },
    { id: 82, name: "Cormorant", bengaliName: "পানকৌড়ি", emoji: "🐦‍⬛", color: "#2F4F4F", type: "Diver" },
    { id: 83, name: "Ibis", bengaliName: "ইবিস", emoji: "🦩", color: "#FFFACD", type: "Wader" },
    { id: 84, name: "Egret", bengaliName: "সাদা বক", emoji: "🦢", color: "#FFFFFF", type: "Elegant" },
    { id: 85, name: "Bittern", bengaliName: "বিটার্ন", emoji: "🦆", color: "#BDB76B", type: "Marsh" },
    { id: 86, name: "Shrike", bengaliName: "শ্রাইক", emoji: "🐦", color: "#808080", type: "Hunter" },
    { id: 87, name: "Bulbul", bengaliName: "বুলবুল", emoji: "🐤", color: "#A0826D", type: "Song" },
    { id: 88, name: "Drongo", bengaliName: "ফিঙে", emoji: "🐦‍⬛", color: "#000000", type: "Bold" },
    { id: 89, name: "Myna", bengaliName: "ময়না", emoji: "🐦", color: "#8B7355", type: "Talker" },
    { id: 90, name: "Weaver Bird", bengaliName: "বাবুই পাখি", emoji: "🦜", color: "#FFD700", type: "Builder" },
    { id: 91, name: "Crossbill", bengaliName: "ক্রসবিল", emoji: "🦜", color: "#DC143C", type: "Unique" },
    { id: 92, name: "Loon", bengaliName: "লুন পাখি", emoji: "🦆", color: "#2F4F4F", type: "Diver" },
    { id: 93, name: "Grebe", bengaliName: "গ্রেব পাখি", emoji: "🦆", color: "#696969", type: "Water" },
    { id: 94, name: "Ptarmigan", bengaliName: "টারমিগান", emoji: "🕊️", color: "#F0F0F0", type: "Arctic" },
    { id: 95, name: "Avocet", bengaliName: "অ্যাভোসেট", emoji: "🦢", color: "#E0E0E0", type: "Wader" },
    { id: 96, name: "Spoonbill", bengaliName: "চামচঠুঁটি", emoji: "🦩", color: "#FFB6C1", type: "Wader" },
    { id: 97, name: "Chickadee", bengaliName: "চিকাডি", emoji: "🐤", color: "#A9A9A9", type: "Cute" },
    { id: 98, name: "Nuthatch", bengaliName: "নাটহ্যাচ", emoji: "🐦", color: "#B0C4DE", type: "Climber" },
    { id: 99, name: "Warbler", bengaliName: "ওয়ারব্লার", emoji: "🐦", color: "#9ACD32", type: "Song" },
    { id: 100, name: "Thrush", bengaliName: "থ্রাশ", emoji: "🐦", color: "#8B6914", type: "Song" }
];
