// ===== Vegetable Learning Data =====
// Contains information about 100 common vegetables

const vegetableDatabase = [
    { id: 1, name: "Potato", bengaliName: "আলু", emoji: "🥔", color: "#C4A35A" },
    { id: 2, name: "Tomato", bengaliName: "টমেটো", emoji: "🍅", color: "#FF6347" },
    { id: 3, name: "Onion", bengaliName: "পিঁয়াজ", emoji: "🧅", color: "#DEB887" },
    { id: 4, name: "Garlic", bengaliName: "রসুন", emoji: "🧄", color: "#F5F5DC" },
    { id: 5, name: "Ginger", bengaliName: "আদা", emoji: "🫚", color: "#DAA520" },
    { id: 6, name: "Carrot", bengaliName: "গাজর", emoji: "🥕", color: "#FF8C00" },
    { id: 7, name: "Cabbage", bengaliName: "বাঁধাকপি", emoji: "🥬", color: "#90EE90" },
    { id: 8, name: "Cauliflower", bengaliName: "ফুলকপি", emoji: "🥦", color: "#F5F5F5" },
    { id: 9, name: "Broccoli", bengaliName: "ব্রকলি", emoji: "🥦", color: "#6B8E23" },
    { id: 10, name: "Spinach", bengaliName: "পালং শাক", emoji: "🥬", color: "#2E8B57" },
    { id: 11, name: "Lettuce", bengaliName: "লেটুস পাতা", emoji: "🥬", color: "#7FFF00" },
    { id: 12, name: "Cucumber", bengaliName: "শসা", emoji: "🥒", color: "#66CDAA" },
    { id: 13, name: "Pumpkin", bengaliName: "মিষ্টি কুমড়া", emoji: "🎃", color: "#FF7518" },
    { id: 14, name: "Radish", bengaliName: "মুলা", emoji: "🥕", color: "#FF69B4" },
    { id: 15, name: "Turnip", bengaliName: "শালগম", emoji: "🥔", color: "#E6E6FA" },
    { id: 16, name: "Beetroot", bengaliName: "বিট", emoji: "🥔", color: "#8B0000" },
    { id: 17, name: "Eggplant", bengaliName: "বেগুন", emoji: "🍆", color: "#663399" },
    { id: 18, name: "Bell Pepper", bengaliName: "ক্যাপসিকাম", emoji: "🫑", color: "#FFD700" },
    { id: 19, name: "Chili Pepper", bengaliName: "মরিচ", emoji: "🌶️", color: "#DC143C" },
    { id: 20, name: "Green Peas", bengaliName: "মটরশুঁটি", emoji: "🫛", color: "#32CD32" },
    { id: 21, name: "Corn", bengaliName: "ভুট্টা", emoji: "🌽", color: "#FFD700" },
    { id: 22, name: "Zucchini", bengaliName: "জুকিনি", emoji: "🥒", color: "#556B2F" },
    { id: 23, name: "Celery", bengaliName: "সেলারি", emoji: "🥬", color: "#8FBC8F" },
    { id: 24, name: "Asparagus", bengaliName: "অ্যাসপারাগাস", emoji: "🥒", color: "#7FFF00" },
    { id: 25, name: "Okra", bengaliName: "ঢেঁড়স", emoji: "🫛", color: "#6B8E23" },
    { id: 26, name: "Bitter Gourd", bengaliName: "করলা", emoji: "🥒", color: "#556B2F" },
    { id: 27, name: "Bottle Gourd", bengaliName: "লাউ", emoji: "🥒", color: "#90EE90" },
    { id: 28, name: "Ridge Gourd", bengaliName: "ঝিঙ্গা", emoji: "🥒", color: "#228B22" },
    { id: 29, name: "Snake Gourd", bengaliName: "চিচিঙ্গা", emoji: "🥒", color: "#9ACD32" },
    { id: 30, name: "Drumstick", bengaliName: "সজনে", emoji: "🥒", color: "#8FBC8F" },
    { id: 31, name: "Sweet Potato", bengaliName: "মিষ্টি আলু", emoji: "🍠", color: "#FF8C69" },
    { id: 32, name: "Yam", bengaliName: "ইয়াম", emoji: "🍠", color: "#A0522D" },
    { id: 33, name: "Taro", bengaliName: "কচু", emoji: "🥔", color: "#8B7D6B" },
    { id: 34, name: "Arugula", bengaliName: "আরুগুলা পাতা", emoji: "🥬", color: "#7CFC00" },
    { id: 35, name: "Kale", bengaliName: "কেল পাতা", emoji: "🥬", color: "#2F4F4F" },
    { id: 36, name: "Leek", bengaliName: "লিক পিঁয়াজ", emoji: "🧅", color: "#C1CDC1" },
    { id: 37, name: "Spring Onion", bengaliName: "পাতা পিঁয়াজ", emoji: "🧅", color: "#98FB98" },
    { id: 38, name: "Shallot", bengaliName: "ছোট পিঁয়াজ", emoji: "🧅", color: "#CD853F" },
    { id: 39, name: "Parsley", bengaliName: "পার্সলে পাতা", emoji: "🌿", color: "#228B22" },
    { id: 40, name: "Coriander", bengaliName: "ধনেপাতা", emoji: "🌿", color: "#32CD32" },
    { id: 41, name: "Mint", bengaliName: "পুদিনা পাতা", emoji: "🌿", color: "#00FF7F" },
    { id: 42, name: "Fenugreek Leaves", bengaliName: "মেথি শাক", emoji: "🌿", color: "#6B8E23" },
    { id: 43, name: "Mustard Greens", bengaliName: "সরিষা শাক", emoji: "🥬", color: "#556B2F" },
    { id: 44, name: "Swiss Chard", bengaliName: "সুইস চার্ড", emoji: "🥬", color: "#ADFF2F" },
    { id: 45, name: "Collard Greens", bengaliName: "কলার্ড শাক", emoji: "🥬", color: "#2E8B57" },
    { id: 46, name: "Brussels Sprouts", bengaliName: "ব্রাসেলস স্প্রাউট", emoji: "🥬", color: "#8FBC8F" },
    { id: 47, name: "Artichoke", bengaliName: "আর্টিচোক", emoji: "🥬", color: "#6B8E23" },
    { id: 48, name: "Endive", bengaliName: "এনডিভ পাতা", emoji: "🥬", color: "#F5F5DC" },
    { id: 49, name: "Bok Choy", bengaliName: "বক চয়", emoji: "🥬", color: "#7FFF00" },
    { id: 50, name: "Watercress", bengaliName: "জলজ শাক", emoji: "🥬", color: "#00FA9A" },
    { id: 51, name: "Fennel", bengaliName: "মৌরি শাক", emoji: "🥬", color: "#F0E68C" },
    { id: 52, name: "Chayote", bengaliName: "চায়োট", emoji: "🥒", color: "#90EE90" },
    { id: 53, name: "Kohlrabi", bengaliName: "কোলরাবি", emoji: "🥬", color: "#E6E6FA" },
    { id: 54, name: "Horseradish", bengaliName: "হর্সরাডিশ", emoji: "🥔", color: "#F5F5DC" },
    { id: 55, name: "Parsnip", bengaliName: "পার্সনিপ", emoji: "🥕", color: "#FFF8DC" },
    { id: 56, name: "Radicchio", bengaliName: "লাল লেটুস", emoji: "🥬", color: "#8B008B" },
    { id: 57, name: "Turnip Greens", bengaliName: "শালগম পাতা", emoji: "🥬", color: "#7CFC00" },
    { id: 58, name: "Dill", bengaliName: "শুলফা পাতা", emoji: "🌿", color: "#7FFF00" },
    { id: 59, name: "Thyme", bengaliName: "থাইম পাতা", emoji: "🌿", color: "#556B2F" },
    { id: 60, name: "Rosemary", bengaliName: "রোজমেরি পাতা", emoji: "🌿", color: "#3CB371" },
    { id: 61, name: "Oregano", bengaliName: "ওরেগানো পাতা", emoji: "🌿", color: "#6B8E23" },
    { id: 62, name: "Basil", bengaliName: "তুলসী পাতা", emoji: "🌿", color: "#228B22" },
    { id: 63, name: "Sage", bengaliName: "সেজ পাতা", emoji: "🌿", color: "#8FBC8F" },
    { id: 64, name: "Turmeric Root", bengaliName: "হলুদ", emoji: "🫚", color: "#FF8C00" },
    { id: 65, name: "Lotus Root", bengaliName: "পদ্ম মূল", emoji: "🥔", color: "#F5DEB3" },
    { id: 66, name: "Green Beans", bengaliName: "সবুজ বিন", emoji: "🫛", color: "#32CD32" },
    { id: 67, name: "Broad Beans", bengaliName: "বড় বিন", emoji: "🫛", color: "#90EE90" },
    { id: 68, name: "Lima Beans", bengaliName: "লিমা বিন", emoji: "🫛", color: "#ADFF2F" },
    { id: 69, name: "Kidney Beans", bengaliName: "কিডনি বিন", emoji: "🫘", color: "#8B0000" },
    { id: 70, name: "Black Beans", bengaliName: "কালো বিন", emoji: "🫘", color: "#2F4F4F" },
    { id: 71, name: "Chickpeas", bengaliName: "ছোলা", emoji: "🫘", color: "#F5DEB3" },
    { id: 72, name: "Soybeans", bengaliName: "সয়াবিন", emoji: "🫘", color: "#F5F5DC" },
    { id: 73, name: "Edamame", bengaliName: "এডামামে", emoji: "🫛", color: "#7FFF00" },
    { id: 74, name: "Peanut", bengaliName: "চীনাবাদাম", emoji: "🥜", color: "#DEB887" },
    { id: 75, name: "Mushroom", bengaliName: "মাশরুম", emoji: "🍄", color: "#D2B48C" },
    { id: 76, name: "Button Mushroom", bengaliName: "বাটন মাশরুম", emoji: "🍄", color: "#F5F5F5" },
    { id: 77, name: "Oyster Mushroom", bengaliName: "ঝিনুক মাশরুম", emoji: "🍄", color: "#F0E68C" },
    { id: 78, name: "Shiitake Mushroom", bengaliName: "শিতাকে মাশরুম", emoji: "🍄", color: "#8B7355" },
    { id: 79, name: "Portobello Mushroom", bengaliName: "পোর্টোবেলো মাশরুম", emoji: "🍄", color: "#8B4513" },
    { id: 80, name: "Seaweed", bengaliName: "সামুদ্রিক শৈবাল", emoji: "🌿", color: "#2F4F4F" },
    { id: 81, name: "Daikon", bengaliName: "সাদা মুলা", emoji: "🥕", color: "#FFFAFA" },
    { id: 82, name: "Scallion", bengaliName: "পাতা পিঁয়াজ", emoji: "🧅", color: "#98FB98" },
    { id: 83, name: "Amaranth Leaves", bengaliName: "লাল শাক", emoji: "🥬", color: "#9932CC" },
    { id: 84, name: "Malabar Spinach", bengaliName: "পুঁই শাক", emoji: "🥬", color: "#2E8B57" },
    { id: 85, name: "Ivy Gourd", bengaliName: "কুন্দুরি", emoji: "🥒", color: "#7CFC00" },
    { id: 86, name: "Cluster Beans", bengaliName: "গোয়ার বিন", emoji: "🫛", color: "#6B8E23" },
    { id: 87, name: "Winged Beans", bengaliName: "ডানাওয়ালা বিন", emoji: "🫛", color: "#90EE90" },
    { id: 88, name: "Ash Gourd", bengaliName: "চাল কুমড়া", emoji: "🥒", color: "#E6E6FA" },
    { id: 89, name: "Red Cabbage", bengaliName: "লাল বাঁধাকপি", emoji: "🥬", color: "#8B008B" },
    { id: 90, name: "Purple Carrot", bengaliName: "বেগুনি গাজর", emoji: "🥕", color: "#9370DB" },
    { id: 91, name: "Yellow Beet", bengaliName: "হলুদ বিট", emoji: "🥔", color: "#FFD700" },
    { id: 92, name: "White Radish", bengaliName: "সাদা মুলা", emoji: "🥕", color: "#FFFAFA" },
    { id: 93, name: "Green Chili", bengaliName: "কাঁচা মরিচ", emoji: "🌶️", color: "#32CD32" },
    { id: 94, name: "Red Chili", bengaliName: "লাল মরিচ", emoji: "🌶️", color: "#DC143C" },
    { id: 95, name: "Jalapeno", bengaliName: "জালাপেনো", emoji: "🌶️", color: "#6B8E23" },
    { id: 96, name: "Habanero", bengaliName: "হাবানেরো", emoji: "🌶️", color: "#FF4500" },
    { id: 97, name: "Sweet Corn", bengaliName: "মিষ্টি ভুট্টা", emoji: "🌽", color: "#F4D03F" },
    { id: 98, name: "Baby Corn", bengaliName: "বেবি কর্ন", emoji: "🌽", color: "#FFEB99" },
    { id: 99, name: "Cherry Tomato", bengaliName: "চেরি টমেটো", emoji: "🍅", color: "#FF6F61" },
    { id: 100, name: "Grape Tomato", bengaliName: "আঙুর টমেটো", emoji: "🍅", color: "#FF7F50" }
];
