// ===== Vegetable Learning Data =====
// Contains information about 100 common vegetables

const vegetableDatabase = [
    { id: 1, name: "Potato", emoji: "🥔", color: "#C4A35A" },
    { id: 2, name: "Tomato", emoji: "🍅", color: "#FF6347" },
    { id: 3, name: "Onion", emoji: "🧅", color: "#DEB887" },
    { id: 4, name: "Garlic", emoji: "🧄", color: "#F5F5DC" },
    { id: 5, name: "Ginger", emoji: "🫚", color: "#DAA520" },
    { id: 6, name: "Carrot", emoji: "🥕", color: "#FF8C00" },
    { id: 7, name: "Cabbage", emoji: "🥬", color: "#90EE90" },
    { id: 8, name: "Cauliflower", emoji: "🥦", color: "#F5F5F5" },
    { id: 9, name: "Broccoli", emoji: "🥦", color: "#6B8E23" },
    { id: 10, name: "Spinach", emoji: "🥬", color: "#2E8B57" },
    { id: 11, name: "Lettuce", emoji: "🥬", color: "#7FFF00" },
    { id: 12, name: "Cucumber", emoji: "🥒", color: "#66CDAA" },
    { id: 13, name: "Pumpkin", emoji: "🎃", color: "#FF7518" },
    { id: 14, name: "Radish", emoji: "🥕", color: "#FF69B4" },
    { id: 15, name: "Turnip", emoji: "🥔", color: "#E6E6FA" },
    { id: 16, name: "Beetroot", emoji: "🥔", color: "#8B0000" },
    { id: 17, name: "Eggplant", emoji: "🍆", color: "#663399" },
    { id: 18, name: "Bell Pepper", emoji: "🫑", color: "#FFD700" },
    { id: 19, name: "Chili Pepper", emoji: "🌶️", color: "#DC143C" },
    { id: 20, name: "Green Peas", emoji: "🫛", color: "#32CD32" },
    { id: 21, name: "Corn", emoji: "🌽", color: "#FFD700" },
    { id: 22, name: "Zucchini", emoji: "🥒", color: "#556B2F" },
    { id: 23, name: "Celery", emoji: "🥬", color: "#8FBC8F" },
    { id: 24, name: "Asparagus", emoji: "🥒", color: "#7FFF00" },
    { id: 25, name: "Okra", emoji: "🫛", color: "#6B8E23" },
    { id: 26, name: "Bitter Gourd", emoji: "🥒", color: "#556B2F" },
    { id: 27, name: "Bottle Gourd", emoji: "🥒", color: "#90EE90" },
    { id: 28, name: "Ridge Gourd", emoji: "🥒", color: "#228B22" },
    { id: 29, name: "Snake Gourd", emoji: "🥒", color: "#9ACD32" },
    { id: 30, name: "Drumstick", emoji: "🥒", color: "#8FBC8F" },
    { id: 31, name: "Sweet Potato", emoji: "🍠", color: "#FF8C69" },
    { id: 32, name: "Yam", emoji: "🍠", color: "#A0522D" },
    { id: 33, name: "Taro", emoji: "🥔", color: "#8B7D6B" },
    { id: 34, name: "Arugula", emoji: "🥬", color: "#7CFC00" },
    { id: 35, name: "Kale", emoji: "🥬", color: "#2F4F4F" },
    { id: 36, name: "Leek", emoji: "🧅", color: "#C1CDC1" },
    { id: 37, name: "Spring Onion", emoji: "🧅", color: "#98FB98" },
    { id: 38, name: "Shallot", emoji: "🧅", color: "#CD853F" },
    { id: 39, name: "Parsley", emoji: "🌿", color: "#228B22" },
    { id: 40, name: "Coriander", emoji: "🌿", color: "#32CD32" },
    { id: 41, name: "Mint", emoji: "🌿", color: "#00FF7F" },
    { id: 42, name: "Fenugreek Leaves", emoji: "🌿", color: "#6B8E23" },
    { id: 43, name: "Mustard Greens", emoji: "🥬", color: "#556B2F" },
    { id: 44, name: "Swiss Chard", emoji: "🥬", color: "#ADFF2F" },
    { id: 45, name: "Collard Greens", emoji: "🥬", color: "#2E8B57" },
    { id: 46, name: "Brussels Sprouts", emoji: "🥬", color: "#8FBC8F" },
    { id: 47, name: "Artichoke", emoji: "🥬", color: "#6B8E23" },
    { id: 48, name: "Endive", emoji: "🥬", color: "#F5F5DC" },
    { id: 49, name: "Bok Choy", emoji: "🥬", color: "#7FFF00" },
    { id: 50, name: "Watercress", emoji: "🥬", color: "#00FA9A" },
    { id: 51, name: "Fennel", emoji: "🥬", color: "#F0E68C" },
    { id: 52, name: "Chayote", emoji: "🥒", color: "#90EE90" },
    { id: 53, name: "Kohlrabi", emoji: "🥬", color: "#E6E6FA" },
    { id: 54, name: "Horseradish", emoji: "🥔", color: "#F5F5DC" },
    { id: 55, name: "Parsnip", emoji: "🥕", color: "#FFF8DC" },
    { id: 56, name: "Radicchio", emoji: "🥬", color: "#8B008B" },
    { id: 57, name: "Turnip Greens", emoji: "🥬", color: "#7CFC00" },
    { id: 58, name: "Dill", emoji: "🌿", color: "#7FFF00" },
    { id: 59, name: "Thyme", emoji: "🌿", color: "#556B2F" },
    { id: 60, name: "Rosemary", emoji: "🌿", color: "#3CB371" },
    { id: 61, name: "Oregano", emoji: "🌿", color: "#6B8E23" },
    { id: 62, name: "Basil", emoji: "🌿", color: "#228B22" },
    { id: 63, name: "Sage", emoji: "🌿", color: "#8FBC8F" },
    { id: 64, name: "Turmeric Root", emoji: "🫚", color: "#FF8C00" },
    { id: 65, name: "Lotus Root", emoji: "🥔", color: "#F5DEB3" },
    { id: 66, name: "Green Beans", emoji: "🫛", color: "#32CD32" },
    { id: 67, name: "Broad Beans", emoji: "🫛", color: "#90EE90" },
    { id: 68, name: "Lima Beans", emoji: "🫛", color: "#ADFF2F" },
    { id: 69, name: "Kidney Beans", emoji: "🫘", color: "#8B0000" },
    { id: 70, name: "Black Beans", emoji: "🫘", color: "#2F4F4F" },
    { id: 71, name: "Chickpeas", emoji: "🫘", color: "#F5DEB3" },
    { id: 72, name: "Soybeans", emoji: "🫘", color: "#F5F5DC" },
    { id: 73, name: "Edamame", emoji: "🫛", color: "#7FFF00" },
    { id: 74, name: "Peanut", emoji: "🥜", color: "#DEB887" },
    { id: 75, name: "Mushroom", emoji: "🍄", color: "#D2B48C" },
    { id: 76, name: "Button Mushroom", emoji: "🍄", color: "#F5F5F5" },
    { id: 77, name: "Oyster Mushroom", emoji: "🍄", color: "#F0E68C" },
    { id: 78, name: "Shiitake Mushroom", emoji: "🍄", color: "#8B7355" },
    { id: 79, name: "Portobello Mushroom", emoji: "🍄", color: "#8B4513" },
    { id: 80, name: "Seaweed", emoji: "🌿", color: "#2F4F4F" },
    { id: 81, name: "Daikon", emoji: "🥕", color: "#FFFAFA" },
    { id: 82, name: "Scallion", emoji: "🧅", color: "#98FB98" },
    { id: 83, name: "Amaranth Leaves", emoji: "🥬", color: "#9932CC" },
    { id: 84, name: "Malabar Spinach", emoji: "🥬", color: "#2E8B57" },
    { id: 85, name: "Ivy Gourd", emoji: "🥒", color: "#7CFC00" },
    { id: 86, name: "Cluster Beans", emoji: "🫛", color: "#6B8E23" },
    { id: 87, name: "Winged Beans", emoji: "🫛", color: "#90EE90" },
    { id: 88, name: "Ash Gourd", emoji: "🥒", color: "#E6E6FA" },
    { id: 89, name: "Red Cabbage", emoji: "🥬", color: "#8B008B" },
    { id: 90, name: "Purple Carrot", emoji: "🥕", color: "#9370DB" },
    { id: 91, name: "Yellow Beet", emoji: "🥔", color: "#FFD700" },
    { id: 92, name: "White Radish", emoji: "🥕", color: "#FFFAFA" },
    { id: 93, name: "Green Chili", emoji: "🌶️", color: "#32CD32" },
    { id: 94, name: "Red Chili", emoji: "🌶️", color: "#DC143C" },
    { id: 95, name: "Jalapeno", emoji: "🌶️", color: "#6B8E23" },
    { id: 96, name: "Habanero", emoji: "🌶️", color: "#FF4500" },
    { id: 97, name: "Sweet Corn", emoji: "🌽", color: "#F4D03F" },
    { id: 98, name: "Baby Corn", emoji: "🌽", color: "#FFEB99" },
    { id: 99, name: "Cherry Tomato", emoji: "🍅", color: "#FF6F61" },
    { id: 100, name: "Grape Tomato", emoji: "🍅", color: "#FF7F50" }
];
